spring:
  application:
    name: demo-mvc
  datasource:
    url: jdbc:postgresql://localhost:5432/clientsdb
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
